bs/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

import bs.core.portal.views as portal_views

admin.site.site_header = 'HPC中心管理（毕设）'
admin.site.site_title = 'HPC中心管理（毕设）'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('robots.txt', TemplateView.as_view(
        template_name='robots.txt', content_type='text/plain'), name="robots"),
    path('', portal_views.home, name='home'),
    path('center-summary', portal_views.center_summary, name='center-summary'),
    path('allocation-summary', portal_views.allocation_summary,
         name='allocation-summary'),
    path('allocation-by-fos', portal_views.allocation_by_fos,
         name='allocation-by-fos'),
    path('user/', include('bs.core.user.urls')),
    path('project/', include('bs.core.project.urls')),
    path('allocation/', include('bs.core.allocation.urls')),
    path('resource/', include('bs.core.resource.urls')),
    path('grant/', include('bs.core.grant.urls')),
    path('publication/', include('bs.core.publication.urls')),
    path('research-output/', include('bs.core.research_output.urls')),
]

if 'django_su.backends.SuBackend' in settings.AUTHENTICATION_BACKENDS:
    urlpatterns.append(path('su/', include('django_su.urls')))

bs/core/grant/urls.py
from django.urls import path

import bs.core.grant.views as grant_views

urlpatterns = [
    path('project/<int:project_pk>/create',
         grant_views.GrantCreateView.as_view(), name='grant-create'),
    path('<int:pk>/update/', grant_views.GrantUpdateView.as_view(),
         name='grant-update'),
    path('project/<int:project_pk>/delete-grants/',
         grant_views.GrantDeleteGrantsView.as_view(), name='grant-delete-grants'),
    path('grant-report/', grant_views.GrantReportView.as_view(), name='grant-report'),
    path('grant-download/', grant_views.GrantDownloadView.as_view(),
         name='grant-download'),
]

bs/core/grant/models.py
from django.db import models
from django.core.validators import (
    MaxLengthValidator, MaxValueValidator, MinLengthValidator)
from model_utils.models import TimeStampedModel
from simple_history.models import HistoricalRecords

from bs.core.project.models import Project


class GrantFundingAgency(TimeStampedModel):
    name = models.CharField(max_length=255, verbose_name="名称")

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = "资助机构"
        verbose_name_plural = "资助机构"


class GrantStatusChoice(TimeStampedModel):
    name = models.CharField(max_length=64, verbose_name="资助状态")

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = "资助状态"
        verbose_name_plural = "资助状态"


class Grant(TimeStampedModel):
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, verbose_name="项目")
    title = models.CharField(
        validators=[MinLengthValidator(3), MaxLengthValidator(255)],
        max_length=255,
        verbose_name="标题"
    )
    grant_number = models.CharField(
        verbose_name='资助机构的授权编号',
        validators=[MinLengthValidator(3), MaxLengthValidator(255)],
        max_length=255,
    )
    ROLE_CHOICES = (
        ('PI', '项目负责人'),
        ('CoPI', '联合负责人'),
        ('SP', '高级人员'),
    )
    role = models.CharField(
        max_length=10,
        choices=ROLE_CHOICES,
        verbose_name="角色"
    )
    grant_pi_full_name = models.CharField(
        max_length=255, blank=True, verbose_name="资助项目负责人名称")
    funding_agency = models.ForeignKey(
        GrantFundingAgency, on_delete=models.CASCADE, verbose_name="资助机构")
    other_funding_agency = models.CharField(
        max_length=255, blank=True, verbose_name="其他资助机构")
    other_award_number = models.CharField(
        max_length=255, blank=True, verbose_name="其他奖励")
    grant_start = models.DateField(verbose_name="资助开始时间")
    grant_end = models.DateField(verbose_name="资助结束时间")
    percent_credit = models.FloatField(
        validators=[MaxValueValidator(100)], verbose_name="占比")
    direct_funding = models.FloatField(verbose_name="直接资助")
    total_amount_awarded = models.FloatField(verbose_name="资助总和")
    status = models.ForeignKey(
        GrantStatusChoice, on_delete=models.CASCADE, verbose_name="状态")
    history = HistoricalRecords(verbose_name="历史")

    @property
    def grant_pi(self):
        if self.role == 'PI':
            return '{}'.format(self.project.pi.first_name)
        else:
            return self.grant_pi_full_name

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Grants"

        permissions = (
            ("can_view_all_grants", "可以查看所有资助"),
        )
        verbose_name = "资助"
        verbose_name_plural = "资助"

bs/core/grant/forms.py
from django import forms
from django.forms import ModelForm
from django.shortcuts import get_object_or_404

from bs.core.grant.models import Grant
from bs.core.utils.common import import_from_settings

CENTER_NAME = import_from_settings('CENTER_NAME')


class GrantForm(ModelForm):
    class Meta:
        model = Grant
        exclude = ['project', ]
        labels = {
            'percent_credit': '{}的信用分百分比'.format(CENTER_NAME),
            'direct_funding': '{}的资助使用情况'.format(CENTER_NAME)
        }
        help_texts = {
            'percent_credit': '按照拨款申请表中填写的百分比信用作为财务信用分配给部门/单位',
            'direct_funding': '资助会用于{}的服务、硬件、软件或人员'.format(CENTER_NAME)
        }

    def __init__(self, *args, **kwargs):
        super(GrantForm, self).__init__(*args, **kwargs)
        self.fields['funding_agency'].queryset = self.fields['funding_agency'].queryset.order_by(
            'name')


class GrantDeleteForm(forms.Form):
    title = forms.CharField(max_length=255, disabled=True)
    grant_number = forms.CharField(
        max_length=30, required=False, disabled=True)
    grant_end = forms.CharField(max_length=150, required=False, disabled=True)
    selected = forms.BooleanField(initial=False, required=False)


class GrantDownloadForm(forms.Form):
    pk = forms.IntegerField(required=False, disabled=True)
    title = forms.CharField(required=False, disabled=True)
    project_pk = forms.IntegerField(required=False, disabled=True)
    pi_first_name = forms.CharField(required=False, disabled=True)
    role = forms.CharField(required=False, disabled=True)
    grant_pi = forms.CharField(required=False, disabled=True)
    total_amount_awarded = forms.FloatField(required=False, disabled=True)
    funding_agency = forms.CharField(required=False, disabled=True)
    grant_number = forms.CharField(required=False, disabled=True)
    grant_start = forms.DateField(required=False, disabled=True)
    grant_end = forms.DateField(required=False, disabled=True)
    percent_credit = forms.FloatField(required=False, disabled=True)
    direct_funding = forms.FloatField(required=False, disabled=True)
    selected = forms.BooleanField(initial=False, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['pk'].widget = forms.HiddenInput()

bs/core/grant/views.py
import csv
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.forms import formset_factory
from django.http import HttpResponseRedirect, StreamingHttpResponse
from django.urls import reverse
from django.views import View
from django.views.generic import FormView, ListView, TemplateView
from django.views.generic.edit import UpdateView

from bs.core.utils.common import Echo
from bs.core.grant.forms import GrantDeleteForm, GrantDownloadForm, GrantForm
from bs.core.grant.models import Grant
from bs.core.project.models import Project


class GrantCreateView(LoginRequiredMixin, UserPassesTestMixin, FormView):
    form_class = GrantForm
    template_name = 'grant/grant_create.html'

    def test_func(self):
        if self.request.user.is_superuser:
            return True

        project_obj = get_object_or_404(
            Project, pk=self.kwargs.get('project_pk'))

        if project_obj.pi == self.request.user:
            return True

        if project_obj.projectuser_set.filter(user=self.request.user, role__name='Manager', status__name='Active').exists():
            return True

        messages.error(
            self.request, '没有权限添加资助。')

    def dispatch(self, request, *args, **kwargs):
        project_obj = get_object_or_404(
            Project, pk=self.kwargs.get('project_pk'))
        if project_obj.status.name not in ['Active', 'New', ]:
            messages.error(
                request, '存档项目不能添加资助。')
            return HttpResponseRedirect(reverse('project-detail', kwargs={'pk': project_obj.pk}))
        else:
            return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form_data = form.cleaned_data
        project_obj = get_object_or_404(
            Project, pk=self.kwargs.get('project_pk'))
        grant_obj = Grant.objects.create(
            project=project_obj,
            title=form_data.get('title'),
            grant_number=form_data.get('grant_number'),
            role=form_data.get('role'),
            grant_pi_full_name=form_data.get('grant_pi_full_name'),
            funding_agency=form_data.get('funding_agency'),
            other_funding_agency=form_data.get('other_funding_agency'),
            other_award_number=form_data.get('other_award_number'),
            grant_start=form_data.get('grant_start'),
            grant_end=form_data.get('grant_end'),
            percent_credit=form_data.get('percent_credit'),
            direct_funding=form_data.get('direct_funding'),
            total_amount_awarded=form_data.get('total_amount_awarded'),
            status=form_data.get('status'),
        )

        return super().form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['project'] = Project.objects.get(
            pk=self.kwargs.get('project_pk'))
        return context

    def get_success_url(self):
        messages.success(self.request, '添加成功。')
        return reverse('project-detail', kwargs={'pk': self.kwargs.get('project_pk')})


class GrantUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    def test_func(self):
        if self.request.user.is_superuser:
            return True

        grant_obj = get_object_or_404(Grant, pk=self.kwargs.get('pk'))

        if grant_obj.project.pi == self.request.user:
            return True

        if grant_obj.project.projectuser_set.filter(user=self.request.user, role__name='Manager', status__name='Active').exists():
            return True

        messages.error(
            self.request, '你没有权限更新项目资助')

    model = Grant
    template_name_suffix = '_update_form'
    fields = ['title', 'grant_number', 'role', 'grant_pi_full_name', 'funding_agency', 'other_funding_agency',
              'other_award_number', 'grant_start', 'grant_end', 'percent_credit', 'direct_funding', 'total_amount_awarded', 'status', ]

    def get_success_url(self):
        return reverse('project-detail', kwargs={'pk': self.object.project.id})


class GrantDeleteGrantsView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    template_name = 'grant/grant_delete_grants.html'

    def test_func(self):
        if self.request.user.is_superuser:
            return True

        project_obj = get_object_or_404(
            Project, pk=self.kwargs.get('project_pk'))

        if project_obj.pi == self.request.user:
            return True

        if project_obj.projectuser_set.filter(user=self.request.user, role__name='Manager', status__name='Active').exists():
            return True

        messages.error(
            self.request, '你没有权限删除项目资助')

    def get_grants_to_delete(self, project_obj):

        grants_to_delete = [

            {'title': grant.title,
             'grant_number': grant.grant_number,
             'grant_end': grant.grant_end}

            for grant in project_obj.grant_set.all()
        ]

        return grants_to_delete

    def get(self, request, *args, **kwargs):
        project_obj = get_object_or_404(
            Project, pk=self.kwargs.get('project_pk'))

        grants_to_delete = self.get_grants_to_delete(project_obj)
        context = {}

        if grants_to_delete:
            formset = formset_factory(
                GrantDeleteForm, max_num=len(grants_to_delete))
            formset = formset(initial=grants_to_delete, prefix='grantform')
            context['formset'] = formset

        context['project'] = project_obj
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        project_obj = get_object_or_404(
            Project, pk=self.kwargs.get('project_pk'))

        grants_to_delete = self.get_grants_to_delete(project_obj)
        context = {}

        formset = formset_factory(
            GrantDeleteForm, max_num=len(grants_to_delete))
        formset = formset(
            request.POST, initial=grants_to_delete, prefix='grantform')

        grants_deleted_count = 0

        if formset.is_valid():
            for form in formset:
                grant_form_data = form.cleaned_data
                if grant_form_data['selected']:

                    grant_obj = Grant.objects.get(
                        project=project_obj,
                        title=grant_form_data.get('title'),
                        grant_number=grant_form_data.get('grant_number')
                    )
                    grant_obj.delete()
                    grants_deleted_count += 1

            messages.success(
                request, '删除{}个资助'.format(grants_deleted_count))
        else:
            for error in formset.errors:
                messages.error(request, error)

        return HttpResponseRedirect(reverse('project-detail', kwargs={'pk': project_obj.pk}))

    def get_success_url(self):
        return reverse('project-detail', kwargs={'pk': self.object.project.id})


class GrantReportView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    template_name = 'grant/grant_report_list.html'

    def test_func(self):
        if self.request.user.is_superuser:
            return True

        if self.request.user.has_perm('grant.can_view_all_grants'):
            return True

        messages.error(
            self.request, '你没有权限查看所有资助')

    def get_grants(self):
        grants = Grant.objects.prefetch_related(
            'project', 'project__pi').all().order_by('-total_amount_awarded')
        grants = [

            {'pk': grant.pk,
             'title': grant.title,
             'project_pk': grant.project.pk,
             'pi_first_name': grant.project.pi.first_name,
             'role': grant.role,
             'grant_pi': grant.grant_pi,
             'total_amount_awarded': grant.total_amount_awarded,
             'funding_agency': grant.funding_agency,
             'grant_number': grant.grant_number,
             'grant_start': grant.grant_start,
             'grant_end': grant.grant_end,
             'percent_credit': grant.percent_credit,
             'direct_funding': grant.direct_funding,
             }
            for grant in grants
        ]

        return grants

    def get(self, request, *args, **kwargs):
        context = {}
        grants = self.get_grants()

        if grants:
            formset = formset_factory(GrantDownloadForm, max_num=len(grants))
            formset = formset(initial=grants, prefix='grantdownloadform')
            context['formset'] = formset
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        grants = self.get_grants()

        formset = formset_factory(GrantDownloadForm, max_num=len(grants))
        formset = formset(request.POST, initial=grants,
                          prefix='grantdownloadform')

        header = [
            '资助标题',
            '项目负责人',
            '角色',
            '资助负责人',
            '资助总和',
            '资助机构',
            '资助机构的授权编号',
            '开始日期',
            '结束日期',
            '信用百分比',
            '资助使用情况',
        ]
        rows = []
        grants_selected_count = 0

        if formset.is_valid():
            for form in formset:
                form_data = form.cleaned_data
                if form_data['selected']:
                    grant = get_object_or_404(Grant, pk=form_data['pk'])

                    row = [
                        grant.title,
                        grant.project.pi.first_name,
                        grant.role,
                        grant.grant_pi_full_name,
                        grant.total_amount_awarded,
                        grant.funding_agency,
                        grant.grant_number,
                        grant.grant_start,
                        grant.grant_end,
                        grant.percent_credit,
                        grant.direct_funding,
                    ]

bs/core/grant/templates/grant/grant_create.html
{% extends 'common/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
创建资助
{% endblock  %}

{% block content %}
  <form method="post">{% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="创建" />
    <a class="btn btn-secondary" href="{% url 'project-detail' project.pk %}" role="button">取消</a><br>
</form>

<script>
 $('#id_grant_start').flatpickr();
 $('#id_grant_end').flatpickr();
</script>


{% endblock %}

bs/core/grant/templates/grant/grant_delete_grants.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
删除资助
{% endblock %}


{% block content %}
<h2>从{{project.title}}中删除</h2>
<hr>

{% if formset %}
  <div class="card border-light">
    <div class="card-body">
      <form action="{% url 'grant-delete-grants' project.pk %}" method="post">
        {% csrf_token %}
        <div class="table-responsive">
          <table class="table table-sm table-hover">
            <thead>
              <tr>
                <th scope="col">
                  <input type="checkbox" class="check" id="selectAll">
                </th>
                <th scope="col">标题</th>
                <th scope="col">资助机构的授权编号</th>
                <th scope="col">结束日期</th>
              </tr>
            </thead>
            <tbody>
              {% for form in formset %}
                <tr>
                  <td>{{ form.selected }}</td>
                  <td>{{ form.title.value }}</td>
                  <td>{{ form.grant_number.value }}</td>
                  <td>{{ form.grant_end.value }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        {{ formset.management_form }}
        <div>
          <button type="submit" class="btn btn-danger"><i class="fas fa-minus" aria-hidden="true"></i> 删除所选</button>
          <a class="btn btn-secondary" href="{% url 'project-detail' project.pk %}" role="button"><i class="fas fa-long-arrow-left" aria-hidden="true"></i> 返回</a>
          <br>
        </div>
      </form>
    </div>
  </div>
{% else %}
  <a class="btn btn-secondary mb-3" href="{% url 'project-detail' project.pk %}" role="button"><i class="fas fa-long-arrow-left" aria-hidden="true"></i> 返回</a>
  <div class="alert alert-info">
    没有可删除资助
  </div>
{% endif %}

<script>
  $("#selectAll").click(function () {
    $("input[name^='grantform-']").prop('checked', $(this).prop('checked'));
  });

  $("input[name^='grantform-']").click(function (ele) {
    var id = $(this).attr('id');
    if ( id != "selectAll") {
      $("#selectAll").prop('checked', false);
    }
  });
</script>
{% endblock %}

bs/core/grant/templates/grant/grant_report_list.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% load humanize %}


{% block title %}
资助报表
{% endblock %}


{% block content %}
<div class="card">
  <div class="card-header">
    <h4 class="d-inline"><i class="fas fa-trophy" aria-hidden="true"></i> 资助</h4>
    <button type="submit" form="download_form" class="btn btn-success float-right"><i class="fas fa-download" aria-hidden="true"></i> 导出为CSV格式</button>
  </div>
  <div class="card-body">
    {% if formset %}
    <form id="download_form" action="{% url 'grant-report' %}" method="post">
      {% csrf_token %}
      <div class="table-responsive">
        <table id="grants-table" class="table table-hover table-sm">
          <thead>
            <tr>
              <th scope="col"><input type="checkbox" class="check" id="selectAll"></th>
              <th scope="col">资助标题</th>
              <th scope="col">项目负责人</th>
              <th scope="col">角色</th>
              <th scope="col">资助负责人</th>
              <th scope="col">资助总和</th>
              <th scope="col">资助机构</th>
              <th scope="col">资助机构的授权编号</th>
              <th scope="col">开始日期</th>
              <th scope="col">结束日期</th>
              <th scope="col">信用百分比</th>
              <th scope="col">资助使用情况</th>
            </tr>
          </thead>
          <tbody>
            {% for form in formset %}
              <tr>
                <td>{{ form.selected }}</td>
                <td style="min-width: 400px">{{ form.title.value }}</td>
                <td class="text-nowrap"><a href="{% url 'project-detail' form.project_pk.value %}">{{ form.pi_first_name.value }}</a></td>
                <td class="text-nowrap">{{ form.role.value }}</td>
                <td class="text-nowrap">{{ form.grant_pi.value }}</td>
                <td class="text-nowrap">{{ form.total_amount_awarded.value|intcomma }}</td>
                <td class="text-nowrap">{{ form.funding_agency.value }}</td>
                <td class="text-nowrap">{{ form.grant_number.value }}</td>
                <td class="text-nowrap">{{ form.grant_start.value|date:"M. d, Y" }}</td>
                <td class="text-nowrap">{{ form.grant_end.value|date:"M. d, Y" }}</td>
                <td>{{ form.percent_credit.value }}</td>
                <td>{{ form.direct_funding.value|intcomma }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      {{ formset.management_form }}
    </form>
    {% else %}
      <div class="alert alert-info" role="alert"><i class="fas fa-info-circle" aria-hidden="true"></i> 没有资助！！！</div>
    {% endif %}
  </div>
</div>

<script>
  $("#navbar-main > ul > li.active").removeClass("active")
  $("#navbar-admin").addClass("active")
  $("#navbar-director").addClass("active")
  $("#navbar-grant-report").addClass("active")
  $(document).ready(function() {
    $('#grants-table').DataTable({
      "iDisplayLength": 50,
      "bSortClasses": false,
      "order": [[ 5, "desc" ]],
      "columnDefs": [{ 'orderable': false, 'targets': 0 }],
      "aaSorting": [[1, 'asc']],
      "language": {
        "sProcessing": "处理中...",
        "sLengthMenu": "显示 _MENU_ 项结果",
        "sZeroRecords": "没有匹配结果",
        "sInfo": "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
        "sInfoEmpty": "显示第 0 至 0 项结果，共 0 项",
        "sInfoFiltered": "(由 _MAX_ 项结果过滤)",
        "sInfoPostFix": "",
        "sSearch": "搜索：",
        "sUrl": "",
        "sEmptyTable": "表中数据为空",
        "sLoadingRecords": "载入中...",
        "sInfoThousands": ",",
        "oPaginate": {
            "sFirst": "首页",
            "sPrevious": "上页",
            "sNext": "下页",
            "sLast": "末页"
        },
        "oAria": {
            "sSortAscending": ": 以升序排列此列",
            "sSortDescending": ": 以降序排列此列"
        }
    }
    });
  });

  $("#selectAll").click(function () {
    $("input[name^='grantdownloadform-']").prop('checked', $(this).prop('checked'));
  });

  $("input[name^='grantdownloadform-']").click(function (ele) {
    var id = $(this).attr('id');
    if (id != "selectAll") {
      $("#selectAll").prop('checked', false);
    }
  });
</script>
{% endblock %}

bs/core/grant/templates/grant/grant_update_form.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
更新资助
{% endblock %}


{% block content %}
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <input class="btn btn-primary" type="submit" value="更新" />
  <a class="btn btn-secondary" href="{% url 'project-detail' object.project.id %}" role="button">取消</a>
</form>

<script>
 $('#id_grant_start').flatpickr();
 $('#id_grant_end').flatpickr();
</script>
{% endblock %}