bs/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

import bs.core.portal.views as portal_views

admin.site.site_header = 'HPC中心管理（毕设）'
admin.site.site_title = 'HPC中心管理（毕设）'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('robots.txt', TemplateView.as_view(
        template_name='robots.txt', content_type='text/plain'), name="robots"),
    path('', portal_views.home, name='home'),
    path('center-summary', portal_views.center_summary, name='center-summary'),
    path('allocation-summary', portal_views.allocation_summary,
         name='allocation-summary'),
    path('allocation-by-fos', portal_views.allocation_by_fos,
         name='allocation-by-fos'),
    path('user/', include('bs.core.user.urls')),
    path('project/', include('bs.core.project.urls')),
    path('allocation/', include('bs.core.allocation.urls')),
    path('resource/', include('bs.core.resource.urls')),
    path('grant/', include('bs.core.grant.urls')),
    path('publication/', include('bs.core.publication.urls')),
    path('research-output/', include('bs.core.research_output.urls')),
]

if 'django_su.backends.SuBackend' in settings.AUTHENTICATION_BACKENDS:
    urlpatterns.append(path('su/', include('django_su.urls')))

bs/core/publication/urls.py
from django.urls import path

import bs.core.publication.views as publication_views

urlpatterns = [
    path('publication-search/<int:project_pk>/',
         publication_views.PublicationSearchView.as_view(), name='publication-search'),
    path('publication-search-result/<int:project_pk>/',
         publication_views.PublicationSearchResultView.as_view(), name='publication-search-result'),
    path('add-publication/<int:project_pk>/',
         publication_views.PublicationAddView.as_view(), name='add-publication'),
    path('add-publication-manually/<int:project_pk>/',
         publication_views.PublicationAddManuallyView.as_view(), name='add-publication-manually'),
    path('project/<int:project_pk>/delete-publications/',
         publication_views.PublicationDeletePublicationsView.as_view(), name='publication-delete-publications'),
    path('project/<int:project_pk>/export-publications/',
         publication_views.PublicationExportPublicationsView.as_view(), name='publication-export-publications'),
]

bs/core/publication/models.py
from django.db import models
from model_utils.models import TimeStampedModel
from simple_history.models import HistoricalRecords

from bs.core.project.models import Project


class PublicationSource(TimeStampedModel):
    name = models.CharField(max_length=255, unique=True, verbose_name="名称")
    url = models.URLField(null=True, blank=True, verbose_name="网址")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "出版物资源"
        verbose_name_plural = "出版物资源"


class Publication(TimeStampedModel):
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, verbose_name="项目")
    title = models.CharField(max_length=1024, verbose_name="标题")
    author = models.CharField(max_length=1024, verbose_name="作者")
    year = models.PositiveIntegerField(verbose_name="年份")
    journal = models.CharField(max_length=1024, verbose_name="期刊")
    unique_id = models.CharField(
        max_length=255, null=True, blank=True, verbose_name="独立ID")
    source = models.ForeignKey(
        PublicationSource, on_delete=models.CASCADE, verbose_name="来源地址")
    STATUS_CHOICES = (
        ('Active', '活跃'),
        ('Archived', '存档'),
    )
    status = models.CharField(
        max_length=16, choices=STATUS_CHOICES, default='Active', verbose_name="状态")
    history = HistoricalRecords(verbose_name="历史")

    class Meta:
        unique_together = ('project', 'unique_id')
        verbose_name = "出版物"
        verbose_name_plural = "出版物"

    def __str__(self):
        return self.title

    def display_uid(self):
        return self.unique_id

bs/core/publication/forms.py
from django import forms

from bs.core.publication.models import PublicationSource


class PublicationAddForm(forms.Form):
    title = forms.CharField(max_length=1024, required=True, label="标题")
    author = forms.CharField(max_length=1024, required=True, label="作者")
    year = forms.IntegerField(
        min_value=1500, max_value=2090, required=True, label="年份")
    journal = forms.CharField(max_length=1024, required=True, label="期刊")
    source = forms.CharField(widget=forms.HiddenInput(), label="来源")


class PublicationSearchForm(forms.Form):
    search_id = forms.CharField(
        label='搜索ID', widget=forms.Textarea, required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['search_id'].help_text = '<br/>输入ID，例如 DOI 或书目代码进行搜索。'


class PublicationResultForm(forms.Form):
    title = forms.CharField(max_length=1024, disabled=True)
    author = forms.CharField(disabled=True)
    year = forms.CharField(max_length=4, disabled=True)
    journal = forms.CharField(max_length=1024, disabled=True)
    unique_id = forms.CharField(max_length=255, disabled=True)
    source_pk = forms.IntegerField(widget=forms.HiddenInput(), disabled=True)
    selected = forms.BooleanField(initial=False, required=False)


class PublicationDeleteForm(forms.Form):
    title = forms.CharField(max_length=255, disabled=True)
    year = forms.CharField(max_length=30, disabled=True)
    selected = forms.BooleanField(initial=False, required=False)


class PublicationExportForm(forms.Form):
    title = forms.CharField(max_length=255, disabled=True)
    year = forms.CharField(max_length=30, disabled=True)
    unique_id = forms.CharField(max_length=255, disabled=True)
    selected = forms.BooleanField(initial=False, required=False)

bs/core/publication/views.py
import re
import uuid
import requests
import io
from bibtexparser.bibdatabase import as_text
from bibtexparser.bparser import BibTexParser
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.forms import formset_factory
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.generic import TemplateView, View
from django.views.generic.edit import FormView

from bs.core.project.models import Project
from bs.core.publication.forms import (
    PublicationAddForm,
    PublicationDeleteForm,
    PublicationResultForm,
    PublicationSearchForm,
    PublicationExportForm,
)
from bs.core.publication.models import Publication, PublicationSource
from doi2bib import crossref

MANUAL_SOURCE = 'manual'


class PublicationSearchView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    template_name = 'publication/publication_add_publication_search.html'

    def test_func(self):
        if self.request.user.is_superuser:
            return True

        project_obj = get_object_or_404(
            Project, pk=self.kwargs.get('project_pk'))

        if project_obj.pi == self.request.user:
            return True

        if project_obj.projectuser_set.filter(user=self.request.user, role__name='Manager', status__name='Active').exists():
            return True

    def dispatch(self, request, *args, **kwargs):
        project_obj = get_object_or_404(
            Project, pk=self.kwargs.get('project_pk'))
        if project_obj.status.name not in ['Active', 'New', ]:
            messages.error(
                request, '存档项目不能添加出版物')
            return HttpResponseRedirect(reverse('project-detail', kwargs={'pk': project_obj.pk}))
        else:
            return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['publication_search_form'] = PublicationSearchForm()
        context['project'] = Project.objects.get(
            pk=self.kwargs.get('project_pk'))
        return context


class PublicationSearchResultView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    template_name = 'publication/publication_add_publication_search_result.html'

    def test_func(self):
        if self.request.user.is_superuser:
            return True

        project_obj = get_object_or_404(
            Project, pk=self.kwargs.get('project_pk'))

        if project_obj.pi == self.request.user:
            return True

        if project_obj.projectuser_set.filter(user=self.request.user, role__name='Manager', status__name='Active').exists():
            return True

    def dispatch(self, request, *args, **kwargs):
        project_obj = get_object_or_404(
            Project, pk=self.kwargs.get('project_pk'))
        if project_obj.status.name not in ['Active', 'New', ]:
            messages.error(
                request, '存档项目不能添加出版物')
            return HttpResponseRedirect(reverse('project-detail', kwargs={'project_pk': project_obj.pk}))
        else:
            return super().dispatch(request, *args, **kwargs)

    def _search_id(self, unique_id):
        matching_source_obj = None
        for source in PublicationSource.objects.all():
            if source.name == 'doi':
                try:
                    status, bib_str = crossref.get_bib(unique_id)
                    bp = BibTexParser(interpolate_strings=False)
                    bib_database = bp.parse(bib_str)
                    bib_json = bib_database.entries[0]
                    matching_source_obj = source
                    break
                except:
                    continue

            elif source.name == 'adsabs':
                try:
                    url = 'http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode={}&data_type=BIBTEX'.format(
                        unique_id)
                    r = requests.get(url, timeout=5)
                    bp = BibTexParser(interpolate_strings=False)
                    bib_database = bp.parse(r.text)
                    bib_json = bib_database.entries[0]
                    matching_source_obj = source
                    break
                except:
                    continue

        if not matching_source_obj:
            return False

        year = as_text(bib_json['year'])
        author = as_text(bib_json['author']).replace('{\\textquotesingle}', "'").replace('{\\textendash}', '-').replace(
            '{\\textemdash}', '-').replace('{\\textasciigrave}', ' ').replace('{\\textdaggerdbl}', ' ').replace('{\\textdagger}', ' ')
        title = as_text(bib_json['title']).replace('{\\textquotesingle}', "'").replace('{\\textendash}', '-').replace(
            '{\\textemdash}', '-').replace('{\\textasciigrave}', ' ').replace('{\\textdaggerdbl}', ' ').replace('{\\textdagger}', ' ')

        author = re.sub("{|}", "", author)
        title = re.sub("{|}", "", title)

        if 'journal' in bib_json:
            journal = as_text(bib_json['journal']).replace('{\\textquotesingle}', "'").replace('{\\textendash}', '-').replace(
                '{\\textemdash}', '-').replace('{\\textasciigrave}', ' ').replace('{\\textdaggerdbl}', ' ').replace('{\\textdagger}', ' ')
            journal = re.sub("{|}", "", journal)
        else:
            source_name = matching_source_obj.name
            journal = '[{}没有期刊信息]'.format(source_name.upper())

        pub_dict = {}
        pub_dict['author'] = author
        pub_dict['year'] = year
        pub_dict['title'] = title
        pub_dict['journal'] = journal
        pub_dict['unique_id'] = unique_id
        pub_dict['source_pk'] = matching_source_obj.pk

        return pub_dict

    def post(self, request, *args, **kwargs):
        search_ids = list(set(request.POST.get('search_id').split()))
        project_pk = self.kwargs.get('project_pk')

        project_obj = get_object_or_404(Project, pk=project_pk)
        pubs = []
        for ele in search_ids:
            pub_dict = self._search_id(ele)
            if pub_dict:
                pubs.append(pub_dict)

        formset = formset_factory(PublicationResultForm, max_num=len(pubs))
        formset = formset(initial=pubs, prefix='pubform')

        context = {}
        context['project_pk'] = project_obj.pk
        context['formset'] = formset
        context['search_ids'] = search_ids
        context['pubs'] = pubs

        return render(request, self.template_name, context)


class PublicationAddView(LoginRequiredMixin, UserPassesTestMixin, View):

    def test_func(self):
        if self.request.user.is_superuser:
            return True

        project_obj = get_object_or_404(
            Project, pk=self.kwargs.get('project_pk'))

        if project_obj.pi == self.request.user:
            return True

        if project_obj.projectuser_set.filter(user=self.request.user, role__name='Manager', status__name='Active').exists():
            return True

    def dispatch(self, request, *args, **kwargs):
        project_obj = get_object_or_404(
            Project, pk=self.kwargs.get('project_pk'))
        if project_obj.status.name not in ['Active', 'New', ]:
            messages.error(
                request, '存档项目不能添加出版物')
            return HttpResponseRedirect(reverse('project-detail', kwargs={'pk': project_obj.pk}))
        else:
            return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        pubs = eval(request.POST.get('pubs'))
        project_pk = self.kwargs.get('project_pk')

        project_obj = get_object_or_404(Project, pk=project_pk)
        formset = formset_factory(PublicationResultForm, max_num=len(pubs))
        formset = formset(request.POST, initial=pubs, prefix='pubform')

        publications_added = 0
        publications_skipped = []
        if formset.is_valid():
            for form in formset:
                form_data = form.cleaned_data

                if form_data['selected']:
                    source_obj = PublicationSource.objects.get(
                        pk=form_data.get('source_pk'))
                    author = form_data.get('author')
                    if len(author) > 1024:
                        author = author[:1024]
                    publication_obj, created = Publication.objects.get_or_create(
                        project=project_obj,
                        unique_id=form_data.get('unique_id'),
                        defaults={
                            'title': form_data.get('title'),
                            'author': author,
                            'year': form_data.get('year'),
                            'journal': form_data.get('journal'),
                            'source': source_obj
                        }
                    )
                    if created:
                        publications_added += 1
                    else:
                        publications_skipped.append(form_data.get('unique_id'))

            msg = ''
            if publications_added:
                msg += '给项目添加 {} 个出版物'.format(
                    publications_added, )
            if publications_skipped:
                msg += '项目已有这些出版物，未添加： {}'.format(
                    ', '.join(publications_skipped))

            messages.success(request, msg)
        else:
            for error in formset.errors:
                messages.error(request, error)

        return HttpResponseRedirect(reverse('project-detail', kwargs={'pk': project_pk}))


class PublicationAddManuallyView(LoginRequiredMixin, UserPassesTestMixin, FormView):
    form_class = PublicationAddForm
    template_name = 'publication/publication_add_publication_manually.html'

    def test_func(self):
        if self.request.user.is_superuser:
            return True

bs/core/publication/templates/publication/publication_add_publication_manually.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
手动添加出版物
{% endblock %}


{% block content %}
<h2>给{{project.title}}添加出版物</h2> <hr>

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {{ form.non_field_errors }}
  </div>
{% endif %}

<div class="row">
  <div class="col">
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <div>
        <button type="submit" class="btn btn-primary"><i class="fas fa-plus" aria-hidden="true"></i> 添加出版物</button>
      </div>
    </form>
  </div>
</div>

<br/>

<div class="row">
  <div class="col">
    <div class="card border-light">
      <div class="card-body">
        <a class="btn btn-info" href="{% url 'publication-search' project.pk %}" role="button">
          <i class="fas fa-search" aria-hidden="true"></i> 返回重新搜索
        </a>
        <a class="btn btn-secondary" href="{% url 'project-detail' project.pk %}" role="button">
          <i class="fas fa-long-arrow-left" aria-hidden="true"></i> 返回
        </a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

bs/core/publication/templates/publication/publication_add_publication_search.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
添加出版物
{% endblock %}


{% block content %}
<h2>给{{project.title}}添加出版物</h2>
<hr>

<div class="col">
  <a class="btn btn-info" href="{% url 'add-publication-manually' project.pk %}" role="button"><i class="far fa-edit" aria-hidden="true"></i> 输入出版物</a>

  <form id="post-form">
    {% csrf_token %}
    {{ publication_search_form|crispy }}
    <button id="search-button" type="submit" class="btn btn-success btn-block"><i class="fas fa-search" aria-hidden="true"></i> 搜索</button>
  </form>
</div>

<br>

<div class="col" id="search_results">
  <div class="card border-light">
    <div class="card-body">
      <div id="search_results_inner"><a class="btn btn-secondary" href="{% url 'project-detail' project_pk %}" role="button">返回</a></div>
    </div>
  </div>
</div>
{% endblock %}


{% block javascript %}
  {{ block.super }}
<script>
  $('#post-form').on('submit', function(event){
    event.preventDefault();
    $('#search_results').show();
    $("#search_results_inner").html('<div class="alert alert-info text-center"><i class="fas fa-sync fa-spin fa-fw" aria-hidden="true"></i> 搜索</div>')
    create_post();
  });

  function create_post() {
    search_id = $('#id_search_id').val().trim();

    var pk = "{{ project.pk }}"
    $.ajax({
        url : "/publication/publication-search-result/" + pk +"/", 
        type : "POST", 
        data : {
          search_id : search_id, 
          csrfmiddlewaretoken: "{{ csrf_token }}"
        }, 
        success : function(data) {
            $('#post-text').val(''); 
            $('#search_results').show();
            $('#search_results_inner').html(data);
        },
        
        error : function(xhr,errmsg,err) {
            $('#results').html("<div class='alert-box alert radius' data-alert>错误辣： "+errmsg+
                " <a href='#' class='close'>&times;</a></div>"); 
            console.log(xhr.status + ": " + xhr.responseText); 
        }
    });
  };

  $(document).ready(function(){
    $('[data-toggle="popover"]').popover(); 
  });
</script>
{% endblock %}

bs/core/publication/templates/publication/publication_add_publication_search_result.html
{% load crispy_forms_tags %}

{% if formset %}
  <div class="card border-light">
    <div class="card-body">
      <form action="{% url 'add-publication' project_pk %}" method="post">
        {% csrf_token %}
        <div class="table-responsive">
          <table class="table table-sm table-hover">
            <thead>
              <tr>
                <th>
                  <input type="checkbox" class="check" id="selectAll">
                </th>
                <th scope="col">#</th>
                <th scope="col">出版物</th>
                <th scope="col">独立ID</th>
              </tr>
            </thead>
            <tbody>
              {% for form in formset %}
                <tr>
                  <td>{{ form.selected }}</td>
                  <td>{{ forloop.counter }}</td>
                  <td>
                    <strong>标题: </strong>{{ form.title.value }} <br>
                    <strong>作者: </strong>{{ form.author.value }} <br> 
                    <strong>年份: </strong>{{ form.year.value }} <br>
                    <strong>期刊: </strong>{{ form.journal.value }}
                  </td>
                  <td class="text-nowrap">{{ form.unique_id.value }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        {{ formset.management_form }}
        <div>
          <button type="submit" class="btn btn-primary"><i class="fas fa-user-minus" aria-hidden="true"></i> 将所选出版物添加到项目</button>
          <a class="btn btn-secondary" href="{% url 'project-detail' project_pk %}" role="button"><i class="fas fa-long-arrow-left" aria-hidden="true"></i> 返回</a>
          <input id="search_ids" type="hidden" name="search_ids" value="{{search_ids}}">
          <input id="pubs" type="hidden" name="pubs" value="{{pubs}}">
        </div>
      </form>
    </div>
  </div>
{% else %}
  <a class="btn btn-secondary mb-3" href="{% url 'project-detail' project.pk %}" role="button"><i class="fas fa-long-arrow-left" aria-hidden="true"></i> 返回</a>
  <div class="alert alert-info">
    没有出版物可删除
  </div>
{% endif %}

<script>
  $("#selectAll").click(function() {
    $("input[name^='pubform-']").prop('checked', $(this).prop('checked'));
  });

  $("input[name^='pubform-']").click(function(ele) {
    var id = $(this).attr('id');
    if (id != "selectAll") {
      $("#selectAll").prop('checked', false);
    }
  });
</script>

bs/core/publication/templates/publication/publication_delete_publications.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
删除出版物
{% endblock %}



{% block content %}
<h2>给{{project.title}}删除出版物</h2>
<hr>

{% if formset %}
  <div class="card border-light">
    <div class="card-body">
      <form action="{% url 'publication-delete-publications' project.pk %}" method="post">
        {% csrf_token %}
        <div class="table-responsive">
          <table class="table table-sm table-hover">
            <thead>
              <tr>
                <th>
                  <input type="checkbox" class="check" id="selectAll">
                </th>
                <th scope="col">标题</th>
                <th scope="col">年份</th>
              </tr>
            </thead>
            <tbody>
              {% for form in formset %}
              <tr>
                <td>{{ form.selected }}</td>
                <td>{{ form.title.value }}</td>
                <td>{{ form.year.value }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        {{ formset.management_form }}
        <div>
          <button type="submit" class="btn btn-danger"><i class="fas fa-minus" aria-hidden="true"></i> 删除所选出版物</button>
          <a class="btn btn-secondary" href="{% url 'project-detail' project.pk %}" role="button"><i class="fas fa-long-arrow-left" aria-hidden="true"></i> 返回</a>
          <br>
        </div>
      </form>
    </div>
  </div>
{% else %}
  <a class="btn btn-secondary mb-3" href="{% url 'project-detail' project.pk %}" role="button"><i class="fas fa-long-arrow-left" aria-hidden="true"></i> 返回</a>
  <div class="alert alert-info">
    没有出版物可删除
  </div>
{% endif %}

<script>
  $(document).ready(function () {
    $("input[name^='publicationform-']").click(function (ele) {
      var id = $(this).attr('id');
      if ( id != "selectAll") {
        $("#selectAll").prop('checked', false);
      }
    });

    $('#selectAll').click(function(e){
      var table= $(e.target).closest('table');
      $('td input:checkbox',table).prop('checked',this.checked);
    });
  });
</script>
{% endblock %}

bs/core/publication/templates/publication/publication_export_publications.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
导出出版物
{% endblock %}


{% block content %}
<h2>从{{project.title}}导出出版物</h2>
<hr>

{% if formset %}
  <div class="card border-light">
    <div class="card-body">
      <form id="export_checkbox" action="{% url 'publication-export-publications' project.pk %}" method="post">
        {% csrf_token %}
        <div class="table-responsive">
          <table class="table table-sm table-hover">
            <thead>
              <tr>
                <th>
                  <input type="checkbox" class="check" id="selectAll">
                </th>
                <th scope="col">标题</th>
                <th scope="col">年份</th>
              </tr>
            </thead>
            <tbody>
              {% for form in formset %}
                <tr>
                  <td>{{ form.selected }}</td>
                  <td>{{ form.title.value }}</td>
                  <td>{{ form.year.value }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        {{ formset.management_form }}
        <div>
          <button type="submit" class="btn btn-success" disabled="disabled" id="submitbtn"><i class="fas fa-file-export" aria-hidden="true"></i> 从项目导出所选出版物</button>
          <a class="btn btn-secondary" href="{% url 'project-detail' project.pk %}" role="button"><i class="fas fa-long-arrow-left" aria-hidden="true"></i> 返回</a>
          <br>
        </div>
      </form>
    </div>
  </div>
{% else %}
  <a class="btn btn-secondary mb-3" href="{% url 'project-detail' project.pk %}" role="button"><i class="fas fa-long-arrow-left" aria-hidden="true"></i> 返回</a>
  <div class="alert alert-info">
    没有出版物可删除
  </div>
{% endif %}

<script>
  $(document).ready(function () {
    $("input[name^='publicationform-']").click(function (ele) {
      var id = $(this).attr('id');
      if ( id != "selectAll") {
        $("#selectAll").prop('checked', false);
      }
    });

    $('#selectAll').click(function(e){
      var table = $(e.target).closest('table');

      $('td input:checkbox',table).prop('checked',this.checked);

      checkboxes.forEach(checkbox => {
        checkbox.addEventListener('click', () => {
          anyChecked()
            ? submitbtn.removeAttribute('disabled')
            : submitbtn.setAttribute('disabled','')
        })
      })

      anyChecked()
            ? submitbtn.removeAttribute('disabled')
            : submitbtn.setAttribute('disabled','')
    });

    $('#selectAll').trigger('click');
  });

  const checkboxes = [...document.querySelectorAll('input[type=checkbox]')]

  function anyChecked() {
    return checkboxes.some(x=>x.checked)
  }
  checkboxes.forEach(checkbox => {
    checkbox.addEventListener('click', () => {
      anyChecked()
        ? submitbtn.removeAttribute('disabled')
        : submitbtn.setAttribute('disabled','')
    })
  })

  anyChecked()
        ? submitbtn.removeAttribute('disabled')
        : submitbtn.setAttribute('disabled','')
</script>
{% endblock %}