bs/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

import bs.core.portal.views as portal_views

admin.site.site_header = 'HPC中心管理（毕设）'
admin.site.site_title = 'HPC中心管理（毕设）'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('robots.txt', TemplateView.as_view(
        template_name='robots.txt', content_type='text/plain'), name="robots"),
    path('', portal_views.home, name='home'),
    path('center-summary', portal_views.center_summary, name='center-summary'),
    path('allocation-summary', portal_views.allocation_summary,
         name='allocation-summary'),
    path('allocation-by-fos', portal_views.allocation_by_fos,
         name='allocation-by-fos'),
    path('user/', include('bs.core.user.urls')),
    path('project/', include('bs.core.project.urls')),
    path('allocation/', include('bs.core.allocation.urls')),
    path('resource/', include('bs.core.resource.urls')),
    path('grant/', include('bs.core.grant.urls')),
    path('publication/', include('bs.core.publication.urls')),
    path('research-output/', include('bs.core.research_output.urls')),
]

if 'django_su.backends.SuBackend' in settings.AUTHENTICATION_BACKENDS:
    urlpatterns.append(path('su/', include('django_su.urls')))

bs/core/allocation/urls.py
from django.urls import path

import bs.core.allocation.views as allocation_views

urlpatterns = [
    path('', allocation_views.AllocationListView.as_view(), name='allocation-list'),
    path('project/<int:project_pk>/create',
         allocation_views.AllocationCreateView.as_view(), name='allocation-create'),
    path('<int:pk>/', allocation_views.AllocationDetailView.as_view(),
         name='allocation-detail'),
    path('change-request/<int:pk>/', allocation_views.AllocationChangeDetailView.as_view(),
         name='allocation-change-detail'),
    path('<int:pk>/delete-attribute-change', allocation_views.AllocationChangeDeleteAttributeView.as_view(),
         name='allocation-attribute-change-delete'),
    path('<int:pk>/add-users', allocation_views.AllocationAddUsersView.as_view(),
         name='allocation-add-users'),
    path('<int:pk>/remove-users', allocation_views.AllocationRemoveUsersView.as_view(),
         name='allocation-remove-users'),
    path('request-list', allocation_views.AllocationRequestListView.as_view(),
         name='allocation-request-list'),
    path('change-list', allocation_views.AllocationChangeListView.as_view(),
         name='allocation-change-list'),
    path('<int:pk>/renew', allocation_views.AllocationRenewView.as_view(),
         name='allocation-renew'),
    path('<int:pk>/allocationattribute/add',
         allocation_views.AllocationAttributeCreateView.as_view(), name='allocation-attribute-add'),
    path('<int:pk>/change-request',
         allocation_views.AllocationChangeView.as_view(), name='allocation-change'),
    path('<int:pk>/allocationattribute/delete',
         allocation_views.AllocationAttributeDeleteView.as_view(), name='allocation-attribute-delete'),
    path('<int:pk>/allocationnote/add',
         allocation_views.AllocationNoteCreateView.as_view(), name='allocation-note-add'),
    path('allocation-invoice-list', allocation_views.AllocationInvoiceListView.as_view(),
         name='allocation-invoice-list'),
    path('<int:pk>/invoice/', allocation_views.AllocationInvoiceDetailView.as_view(),
         name='allocation-invoice-detail'),
    path('allocation/<int:pk>/add-invoice-note',
         allocation_views.AllocationAddInvoiceNoteView.as_view(), name='allocation-add-invoice-note'),
    path('allocation-invoice-note/<int:pk>/update',
         allocation_views.AllocationUpdateInvoiceNoteView.as_view(), name='allocation-update-invoice-note'),
    path('allocation/<int:pk>/invoice/delete/',
         allocation_views.AllocationDeleteInvoiceNoteView.as_view(), name='allocation-delete-invoice-note'),
    path('add-allocation-account/', allocation_views.AllocationAccountCreateView.as_view(),
         name='add-allocation-account'),
    path('allocation-account-list/', allocation_views.AllocationAccountListView.as_view(),
         name='allocation-account-list'),
]

bs/core/allocation/models.py
import datetime
import logging
from ast import literal_eval
from enum import Enum
from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.html import mark_safe
from django.utils.module_loading import import_string
from model_utils.models import TimeStampedModel
from simple_history.models import HistoricalRecords
from bs.core.project.models import Project, ProjectPermission
from bs.core.resource.models import Resource
from bs.core.utils.common import import_from_settings
import bs.core.attribute_expansion as attribute_expansion

logger = logging.getLogger(__name__)

ALLOCATION_ATTRIBUTE_VIEW_LIST = import_from_settings(
    'ALLOCATION_ATTRIBUTE_VIEW_LIST', [])
ALLOCATION_FUNCS_ON_EXPIRE = import_from_settings(
    'ALLOCATION_FUNCS_ON_EXPIRE', [])
ALLOCATION_RESOURCE_ORDERING = import_from_settings(
    'ALLOCATION_RESOURCE_ORDERING',
    ['-is_allocatable', 'name'])


class AllocationPermission(Enum):
    USER = 'USER'
    MANAGER = 'MANAGER'


class AllocationStatusChoice(TimeStampedModel):
    name = models.CharField(max_length=64, verbose_name="名称")

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name', ]
        verbose_name = "分配状态"
        verbose_name_plural = "分配状态"


class Allocation(TimeStampedModel):
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, verbose_name="项目")
    resources = models.ManyToManyField(Resource, verbose_name="资源")
    status = models.ForeignKey(
        AllocationStatusChoice, on_delete=models.CASCADE, verbose_name='状态')
    quantity = models.IntegerField(default=1, verbose_name="数量")
    start_date = models.DateField(blank=True, null=True, verbose_name="开始日期")
    end_date = models.DateField(blank=True, null=True, verbose_name="结束日期")
    justification = models.TextField(verbose_name="理由")
    description = models.CharField(
        max_length=512, blank=True, null=True, verbose_name="描述")
    is_locked = models.BooleanField(default=False, verbose_name="是否锁定")
    is_changeable = models.BooleanField(default=False, verbose_name="是否可变")
    history = HistoricalRecords(verbose_name="历史")

    class Meta:
        ordering = ['end_date', ]
        verbose_name = "分配资源"
        verbose_name_plural = "分配资源"

        permissions = (
            ('can_view_all_allocations', '可以查看分配'),
            ('can_review_allocation_requests',
             '可以审核所有分配请求'),
            ('can_manage_invoice', '可以管理账单'),
        )

    def clean(self):
        if self.status.name == 'Expired':
            if not self.end_date:
                raise ValidationError('必须填写结束日期')

            if self.end_date > datetime.datetime.now().date():
                raise ValidationError(
                    '结束日期不能大于今天')

            if self.start_date > self.end_date:
                raise ValidationError(
                    '开始日期不能大于结束日期')

        elif self.status.name == 'Active':
            if not self.start_date:
                raise ValidationError('你必须设置开始日期')

            if not self.end_date:
                raise ValidationError('你必须设置结束日期')

            if self.start_date > self.end_date:
                raise ValidationError(
                    '开始日期不能大于结束日期')

    def save(self, *args, **kwargs):
        if self.pk:
            old_obj = Allocation.objects.get(pk=self.pk)
            if old_obj.status.name != self.status.name and self.status.name == 'Expired':
                for func_string in ALLOCATION_FUNCS_ON_EXPIRE:
                    func_to_run = import_string(func_string)
                    func_to_run(self.pk)

        super().save(*args, **kwargs)

    @property
    def expires_in(self):
        return (self.end_date - datetime.date.today()).days

    @property
    def get_information(self):
        html_string = ''
        for attribute in self.allocationattribute_set.all():
            if attribute.allocation_attribute_type.name in ALLOCATION_ATTRIBUTE_VIEW_LIST:
                html_string += '%s: %s <br>' % (
                    attribute.allocation_attribute_type.name, attribute.value)

            if hasattr(attribute, 'allocationattributeusage'):
                try:
                    percent = round(float(attribute.allocationattributeusage.value) /
                                    float(attribute.value) * 10000) / 100
                except ValueError:
                    percent = '无效值'
                    logger.error(" '%s' 不是int类型",
                                 attribute.allocation_attribute_type.name)
                except ZeroDivisionError:
                    percent = 100
                    logger.error(" '%s' 等于0但是又用法",
                                 attribute.allocation_attribute_type.name)

                string = '{}: {}/{} ({} %) <br>'.format(
                    attribute.allocation_attribute_type.name,
                    attribute.allocationattributeusage.value,
                    attribute.value,
                    percent
                )
                html_string += string

        return mark_safe(html_string)

    @property
    def get_resources_as_string(self):
        return ', '.join([ele.name for ele in self.resources.all().order_by(
            *ALLOCATION_RESOURCE_ORDERING)])

    @property
    def get_resources_as_list(self):
        return [ele for ele in self.resources.all().order_by('-is_allocatable')]

    @property
    def get_parent_resource(self):
        if self.resources.count() == 1:
            return self.resources.first()
        else:
            parent = self.resources.order_by(
                *ALLOCATION_RESOURCE_ORDERING).first()
            if parent:
                return parent
            return self.resources.first()

    def get_attribute(self, name, expand=True, typed=True,
                      extra_allocations=[]):
        attr = self.allocationattribute_set.filter(
            allocation_attribute_type__name=name).first()
        if attr:
            if expand:
                return attr.expanded_value(
                    extra_allocations=extra_allocations, typed=typed)
            else:
                if typed:
                    return attr.typed_value()
                else:
                    return attr.value
        return None

    def set_usage(self, name, value):
        attr = self.allocationattribute_set.filter(
            allocation_attribute_type__name=name).first()
        if not attr:
            return

        if not attr.allocation_attribute_type.has_usage:
            return

        if not AllocationAttributeUsage.objects.filter(allocation_attribute=attr).exists():
            usage = AllocationAttributeUsage.objects.create(
                allocation_attribute=attr)
        else:
            usage = attr.allocationattributeusage

        usage.value = value
        usage.save()

    def get_attribute_list(self, name, expand=True, typed=True,
                           extra_allocations=[]):
        attr = self.allocationattribute_set.filter(
            allocation_attribute_type__name=name).all()
        if expand:
            return [a.expanded_value(typed=typed,
                                     extra_allocations=extra_allocations) for a in attr]
        else:
            if typed:
                return [a.typed_value() for a in attr]
            else:
                return [a.value for a in attr]

    def get_attribute_set(self, user):
        if user.is_superuser:
            return self.allocationattribute_set.all().order_by('allocation_attribute_type__name')

        return self.allocationattribute_set.filter(allocation_attribute_type__is_private=False).order_by('allocation_attribute_type__name')

    def user_permissions(self, user):
        if user.is_superuser:
            return list(AllocationPermission)

        project_perms = self.project.user_permissions(user)

        if ProjectPermission.USER not in project_perms:
            return []

        if ProjectPermission.PI in project_perms or ProjectPermission.MANAGER in project_perms:
            return [AllocationPermission.USER, AllocationPermission.MANAGER]

        if self.allocationuser_set.filter(user=user, status__name__in=['Active', 'New', ]).exists():
            return [AllocationPermission.USER]

        return []

    def has_perm(self, user, perm):
        perms = self.user_permissions(user)
        return perm in perms

    def __str__(self):
        return "%s (%s)" % (self.get_parent_resource.name, self.project.pi)


class AllocationAdminNote(TimeStampedModel):
    allocation = models.ForeignKey(
        Allocation, on_delete=models.CASCADE, verbose_name="分配")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="管理员")
    note = models.TextField(verbose_name="描述")

    def __str__(self):
        return self.note

    class Meta:
        verbose_name = "分配管理员描述"
        verbose_name_plural = "分配管理员描述"


class AllocationUserNote(TimeStampedModel):
    allocation = models.ForeignKey(
        Allocation, on_delete=models.CASCADE, verbose_name="分配")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="用户")
    is_private = models.BooleanField(default=True, verbose_name="是否私人")
    note = models.TextField(verbose_name="描述")

    def __str__(self):
        return self.note

    class Meta:
        verbose_name = "分配人员描述"
        verbose_name_plural = "分配人员描述"


class AttributeType(TimeStampedModel):

    name = models.CharField(max_length=64, verbose_name="名称")

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name', ]
        verbose_name = "分配属性"
        verbose_name_plural = "分配属性"


class AllocationAttributeType(TimeStampedModel):
    attribute_type = models.ForeignKey(
        AttributeType, on_delete=models.CASCADE, verbose_name="属性类型")
    name = models.CharField(max_length=50, verbose_name="名称")

bs/core/allocation/templates/allocation/allocation_add_invoice_note.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
添加分配账单描述
{% endblock %}


{% block content %}
<h2>给{{allocation.get_resources_as_string}}添加分配账单描述，项目负责人为{{allocation.project.pi.username}}</h2>
<hr>

<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <input class="btn btn-success" type="submit" value="添加">
  <a class="btn btn-secondary" href="{% url 'allocation-invoice-detail' allocation.pk %}" role="button">返回</a>
</form>
{% endblock %}

bs/core/allocation/templates/allocation/allocation_add_users.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
Add Users to Allocation
{% endblock %}


{% block content %}
<h2>Add users to allocation for project: {{allocation.project.title}}</h2>
<hr>

{% if formset %}
  <div class="card border-light">
    <div class="card-body">
      <form action="{% url 'allocation-add-users' allocation.pk %}" method="post">
        {% csrf_token %}
        <div class="table-responsive">
          <table class="table table-sm table-hover">
            <thead>
              <tr>
                <th>
                  <input type="checkbox" class="check" id="selectAll">
                </th>
                <th scope="col">#</th>
                <th scope="col">Username</th>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Email</th>
              </tr>
            </thead>
            <tbody>
              {% for form in formset %}
                <tr>
                  <td>{{ form.selected }}</td>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ form.username.value }}</td>
                  <td>{{ form.first_name.value }}</td>
                  <td>{{ form.last_name.value }}</td>
                  <td>{{ form.email.value }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        {{ formset.management_form }}
        <div>
          <button type="submit" class="btn btn-primary"><i class="fas
              fa-user-plus"></i> Add Selected Users to Allocation</button>
          <a class="btn btn-secondary" href="{% url 'allocation-detail' allocation.pk %}" role="button"><i class="fas fa-long-arrow-left" aria-hidden="true"></i>
            Back to Allocation</a>
          <br>
        </div>
      </form>
    </div>
  </div>
{% else %}
  <a class="btn btn-secondary mb-3" href="{% url 'allocation-detail' allocation.pk %}" role="button"><i class="fas fa-long-arrow-left" aria-hidden="true"></i> Back to Allocation</a>
  <div class="alert alert-info">
    All users in project are already in this allocation!
  </div>
{% endif %}

<script>
  $("#selectAll").click(function () {
    $("input[name^='userform-']").prop('checked', $(this).prop('checked'));
  });

  $("input[name^='userform-']").click(function (ele) {
    var id = $(this).attr('id');
    if ( id != "selectAll") {
      $("#selectAll").prop('checked', false);
    }
  });
</script>
{% endblock %}

bs/core/allocation/templates/allocation/allocation_allocationaccount_create.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load common_tags %}
{% load static %}


{% block title %}
请求新分配
{% endblock %}


{% block content %}
<h2>添加可与分配关联的帐户</h2>

<form method="post">
  {% csrf_token %}
  {{form |crispy}}
  <input class="btn btn-primary" type="submit" value="提交" />
  <a class="btn btn-secondary" href="{% url 'allocation-account-list' %}" role="button">返回</a><br>
</form>
{% endblock %}

bs/core/allocation/templates/allocation/allocation_allocationattribute_delete.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
删除分配属性
{% endblock %}


{% block content %}
<h2>从{{allocation.project.title}}删除分配属性</h2>
<hr>

{% if formset %}
  <div class="card border-light">
    <div class="card-body">
      <form action="{% url 'allocation-attribute-delete' allocation.pk %}" method="post">
        {% csrf_token %}
        <div class="table-responsive">
          <table class="table table-sm table-hover">
            <thead>
              <tr>
                <th>
                  <input type="checkbox" class="check" id="selectAll">
                </th>
                <th scope="col">名称</th>
                <th scope="col">值</th>
              </tr>
            </thead>
            <tbody>
              {% for form in formset %}
                <tr>
                  <td>{{ form.selected }}</td>
                  <td>{{ form.name.value }}</td>
                  <td>{{ form.value.value }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        {{ formset.management_form }}
        <div>
          <button type="submit" class="btn btn-danger"><i class="fas fa-minus" aria-hidden="true"></i> 删除所选属性</button>
          <a class="btn btn-secondary" href="{% url 'allocation-detail' allocation.pk %}" role="button"><i
              class="fas fa-long-arrow-left" aria-hidden="true"></i> 返回</a>
          <br>
        </div>
      </form>
    </div>
  </div>
{% else %}
  <a class="btn btn-secondary mb-3" href="{% url 'allocation-detail' allocation.pk %}" role="button"><i
      class="fas fa-long-arrow-left" aria-hidden="true"></i> 返回</a>
  <div class="alert alert-info">
    没有属性可删除！
  </div>
{% endif %}

<script>
  $("#selectAll").click(function () {
    $("input[name^='attributeform-']").prop('checked', $(this).prop('checked'));
  });

  $("input[name^='attributeform-']").click(function (ele) {
    var id = $(this).attr('id');
    if (id != "selectAll") {
      $("#selectAll").prop('checked', false);
    }
  });
</script>
{% endblock %}

bs/core/allocation/templates/allocation/allocation_invoice_detail.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
分配账单信息
{% endblock %}


{% block content %}
{% if allocation.project.status.name == 'Archived' %}
  <div class="alert alert-warning" role="alert">
    这个项目已封存，不能进行修改。
  </div>
{% endif %}

<div class="mb-3">
  <h2>分配账单</h2>
  <hr>
</div>

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {{ form.non_field_errors }}
  </div>
{% endif %}

<div class="card mb-3">
  <div class="card-header">
    <h3><i class="fas fa-list" aria-hidden="true"></i> 分配信息</h3>
  </div>
  <div class="card-body">
    <form method="post">
      {% csrf_token %}
      <div class="table-responsive">
        <table class="table table-bordered table-sm">
          <tr>
            <th scope="row" class="text-nowrap">项目:</th>
            <td>
              {% if request.user.is_superuser %}
                <a href="{% url 'project-detail' allocation.project.pk %}">{{ allocation.project }}</a>
              {% else %}
                {{ allocation.project }}
              {% endif %}
            </td>
          </tr>
          <tr>
            <th scope="row" class="text-nowrap">项目负责人:</th>
            <td>
              {{ allocation.project.pi.first_name }}
              ({{ allocation.project.pi.email }})
            </td>
          </tr>
          <tr>
            <th scope="row" class="text-nowrap">资源{{ allocation.resources.all|pluralize }}:</th>
            <td>{{ allocation.get_resources_as_string }}</td>
          </tr>
          <tr>
            <th scope="row" class="text-nowrap">数量:</th>
            <td>
              {{ allocation.quantity }}
            </td>
          </tr>
          <tr>
            <th scope="row" class="text-nowrap">状态:</th>
            <td>
              {{ form.status }}
            </td>
          </tr>
          <tr>
            <th scope="row" class="text-nowrap">创建日期:</th>
            <td>{{ allocation.created }}</td>
          </tr>
          <tr>
            <th scope="row" class="text-nowrap">修改日期:</th>
            <td>{{ allocation.modified }}</td>
          </tr>
        </table>
      </div>
      {% if request.user.is_superuser or perms.allocation.can_manage_invoice%}
        <button type="submit" class="btn btn-success float-right"><i class="fas fa-sync" aria-hidden="true"></i> 更新</button>
      {% endif %}
    </form>
  </div>
</div>

<div class="card mb-3">
  <div class="card-header">
    <h3 class="d-inline"><i class="fas fa-users" aria-hidden="true"></i> 系统管理员的描述</h3>
    <span class="badge badge-secondary">{{allocation.allocationusernote_set.count}}</span>
    <div class="float-right">
      <a class="btn btn-success" href="{% url 'allocation-add-invoice-note' allocation.pk %}" role="button">
        <i class="fas fa-plus" aria-hidden="true"></i> 添加描述
      </a>
      <a class="btn btn-danger" href="{% url 'allocation-delete-invoice-note' allocation.pk %}" role="button">
        <i class="fas fa-minus" aria-hidden="true"></i> 删除描述
      </a>
    </div>
  </div>
  <div class="card-body">
    {% if allocation.allocationusernote_set.all %}
      <div class="table-responsive">
        <table class="table table-hover">
          <thead>
            <tr>
              <th scope="col">内容</th>
              <th scope="col">描述人</th>
              <th scope="col">修改日期</th>
              <th scope="col">操作</th>
            </tr>
          </thead>
          <tbody>
            {% for note in allocation.allocationusernote_set.all %}
              <tr>
                <td>{{ note.note }}</td>
                <td>{{ note.author.first_name }}({{ note.author.username }})</td>
                <td>{{ note.modified }}</td>
                <td><a href="{% url 'allocation-update-invoice-note' note.pk %}"><i class="fas fa-edit" aria-hidden="true"></i><span class="sr-only">编辑</span></a></td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    {% else %}
      <div class="alert alert-info" role="alert">
        <i class="fa fa-info-circle" aria-hidden="true"></i> 没有来自系统管理员的信息
      </div>
    {% endif %}
  </div>
</div>
{% endblock %}

bs/core/allocation/templates/allocation/allocation_invoice_list.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
分配账单表
{% endblock %}


{% block content %}
<h2>需要付款的分配</h2>

{% if allocation_list %}
  <div class="table-responsive">
    <table class="table table-sm">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">资源</th>
          <th scope="col">状态</th>
          <th scope="col">项目负责人</th>
        </tr>
      </thead>
      <tbody>
        {% for allocation in allocation_list %}
          <tr>
            <td><a href="{% url 'allocation-invoice-detail' allocation.pk %}">{{allocation.pk}}</td>
            <td>{{allocation.get_resources_as_string}}</td>
            <td>{{allocation.status}}</td>
            <td>{{allocation.project.pi.username }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% else %}
  <div class="alert alert-info">
    没有需要付款的分配
  </div>
{% endif %}
{% endblock %}

bs/core/allocation/templates/allocation/allocation_note_create.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load common_tags %}
{% load static %}


{% block title %}
添加分配描述
{% endblock %}


{% block content %}
<h2>给{{allocation.get_parent_resource}}添加分配描述，项目负责人为{{ allocation.project.pi.first_name }} ({{ allocation.project.pi.username }})</h2>

<form method="post">
  {% csrf_token %}
  {{form |crispy}}
  <input class="btn btn-success" type="submit" value="添加" />
  <a class="btn btn-secondary" href="{% url 'allocation-detail' allocation.pk %}" role="button">返回</a><br>
</form>
{% endblock %}

bs/core/allocation/templates/allocation/allocation_request_list.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load common_tags %}
{% load static %}


{% block title %}
审核分配请求
{% endblock %}


{% block content %}
<h2>分配请求</h2>

<hr>

<p class="text-justify"> 
  对于下面的每个分配请求，可以选择激活分配请求并查看分配的详细信息页面。
</p>

<p class="text-justify"> 
  默认情况下，分配将激活{{ ALLOCATION_DEFAULT_ALLOCATION_LENGTH }}天。
</p>

{% if allocation_list %}
  <div class="table-responsive">
    <table class="table table-sm">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">请求日期</th>
          <th scope="col">项目标题</th>
          <th scope="col">项目负责人</th>
          <th scope="col">资源</th>
          {% if PROJECT_ENABLE_PROJECT_REVIEW %}
            <th scope="col" class="text-nowrap">项目审核状态</th>
          {% endif %}
          <th scope="col">状态</th>
          <th scope="col">操作</th>
        </tr>
      </thead>
      <tbody>
        {% for allocation in allocation_list %}
          <tr>
            <td>{{allocation.pk}}</td>
            <td>{{ allocation.created|date:"M. d, Y" }}</td>
            <td><a href="{% url 'project-detail' allocation.project.pk %}">{{allocation.project.title|truncatechars:50}}</a></td>
            <td>{{allocation.project.pi.first_name}}({{allocation.project.pi.username}})</td>
            <td>{{allocation.get_parent_resource}}</td>
            {% if PROJECT_ENABLE_PROJECT_REVIEW %}
              <td class="text-center">{{allocation.project|convert_status_to_icon}}</td>
            {% endif %}
            <td>{{allocation.status}}</td>
            <td class="text-nowrap">
                <form method="post" action="{% url 'allocation-detail' allocation.pk %}">
                  {% csrf_token %}
                  <input type="hidden" name="status" value="{{ allocation_status_active.id }}" />
                  <button type="submit" name="action" value="auto-approve" class="btn btn-success mr-1{% if allocation.get_information == '' %} confirm-activate{% endif %}">同意</button>
                  <a href="{% url 'allocation-detail' allocation.pk %}" class="btn btn-primary mr-1">详细信息</a>
                </form>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% else %}
  <div class="alert alert-info">
    没有分配请求
  </div>
{% endif %}

<script>
  $("#navbar-main > ul > li.active").removeClass("active");
  $("#navbar-admin").addClass("active");
  $("#navbar-allocation-requests").addClass("active");
  $(document).on('click', '.confirm-activate', function(){
      return confirm('是否要在不设置任何分配属性的情况下激活此分配请求？');
  })
</script>
{% endblock %}