bs/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

import bs.core.portal.views as portal_views

admin.site.site_header = 'HPC中心管理（毕设）'
admin.site.site_title = 'HPC中心管理（毕设）'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('robots.txt', TemplateView.as_view(
        template_name='robots.txt', content_type='text/plain'), name="robots"),
    path('', portal_views.home, name='home'),
    path('center-summary', portal_views.center_summary, name='center-summary'),
    path('allocation-summary', portal_views.allocation_summary,
         name='allocation-summary'),
    path('allocation-by-fos', portal_views.allocation_by_fos,
         name='allocation-by-fos'),
    path('user/', include('bs.core.user.urls')),
    path('project/', include('bs.core.project.urls')),
    path('allocation/', include('bs.core.allocation.urls')),
    path('resource/', include('bs.core.resource.urls')),
    path('grant/', include('bs.core.grant.urls')),
    path('publication/', include('bs.core.publication.urls')),
    path('research-output/', include('bs.core.research_output.urls')),
]

if 'django_su.backends.SuBackend' in settings.AUTHENTICATION_BACKENDS:
    urlpatterns.append(path('su/', include('django_su.urls')))

bs/core/project/urls.py
from django.urls import path

import bs.core.project.views as project_views

urlpatterns = [
    path('<int:pk>/', project_views.ProjectDetailView.as_view(),
         name='project-detail'),
    path('<int:pk>/archive', project_views.ProjectArchiveProjectView.as_view(),
         name='project-archive'),
    path('', project_views.ProjectListView.as_view(), name='project-list'),
    path('project-user-update-email-notification/', project_views.project_update_email_notification,
         name='project-user-update-email-notification'),
    path('archived/', project_views.ProjectArchivedListView.as_view(),
         name='project-archived-list'),
    path('create/', project_views.ProjectCreateView.as_view(), name='project-create'),
    path('<int:pk>/update/', project_views.ProjectUpdateView.as_view(),
         name='project-update'),
    path('<int:pk>/add-users-search/', project_views.ProjectAddUsersSearchView.as_view(),
         name='project-add-users-search'),
    path('<int:pk>/add-users-search-results/', project_views.ProjectAddUsersSearchResultsView.as_view(),
         name='project-add-users-search-results'),
    path('<int:pk>/add-users/', project_views.ProjectAddUsersView.as_view(),
         name='project-add-users'),
    path('<int:pk>/remove-users/', project_views.ProjectRemoveUsersView.as_view(),
         name='project-remove-users'),
    path('<int:pk>/user-detail/<int:project_user_pk>',
         project_views.ProjectUserDetail.as_view(), name='project-user-detail'),
    path('<int:pk>/review/', project_views.ProjectReviewView.as_view(),
         name='project-review'),
    path('project-review-list', project_views.ProjectReviewListView.as_view(),
         name='project-review-list'),
    path('project-review-complete/<int:project_review_pk>/', project_views.ProjectReviewCompleteView.as_view(),
         name='project-review-complete'),
    path('project-review/<int:pk>/email',
         project_views.ProjectReivewEmailView.as_view(), name='project-review-email'),
    path('<int:pk>/projectnote/add',
         project_views.ProjectNoteCreateView.as_view(), name='project-note-add'),
    path('<int:pk>/project-attribute-create/',
         project_views.ProjectAttributeCreateView.as_view(), name='project-attribute-create'),
    path('<int:pk>/project-attribute-delete/',
         project_views.ProjectAttributeDeleteView.as_view(), name='project-attribute-delete'),
    path('<int:pk>/project-attribute-update/<int:project_attribute_pk>',
         project_views.ProjectAttributeUpdateView.as_view(), name='project-attribute-update'),
]

bs/core/project/models.py
import datetime
import textwrap
from enum import Enum

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.db import models
from ast import literal_eval
from bs.core.utils.validate import AttributeValidator
from model_utils.models import TimeStampedModel
from simple_history.models import HistoricalRecords
from bs.core.utils.common import import_from_settings
from bs.core.field_of_science.models import FieldOfScience

PROJECT_ENABLE_PROJECT_REVIEW = import_from_settings(
    'PROJECT_ENABLE_PROJECT_REVIEW', False)


class ProjectPermission(Enum):
    USER = 'user'
    MANAGER = 'manager'
    PI = 'pi'
    UPDATE = 'update'


class ProjectStatusChoice(TimeStampedModel):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = "项目状态"
        verbose_name_plural = "项目状态"


class Project(TimeStampedModel):

    DEFAULT_DESCRIPTION = "我们没有关于您的研究信息。请提供工作的详细描述并更新您的学科领域。谢谢！"

    title = models.CharField(max_length=255, verbose_name="项目标题")
    pi = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="项目负责人")
    description = models.TextField(
        default=DEFAULT_DESCRIPTION,
        validators=[
            MinLengthValidator(10, "项目描述必须多于10个字。")
        ],
        verbose_name="项目描述"
    )

    field_of_science = models.ForeignKey(
        FieldOfScience, on_delete=models.CASCADE, default=000, verbose_name="学科领域")
    status = models.ForeignKey(
        ProjectStatusChoice, on_delete=models.CASCADE, verbose_name="项目状态")
    force_review = models.BooleanField(default=False, verbose_name="强制审核")
    requires_review = models.BooleanField(default=True, verbose_name="需求审核")
    history = HistoricalRecords()

    def clean(self):
        if "添加项目标题" in self.title:
            raise ValidationError('请输入项目标题')

        if "我们没有关于您的研究信息。请提供工作的详细描述并更新您的学科领域。谢谢！" in self.description:
            raise ValidationError('请输入项目描述')

    @property
    def last_project_review(self):
        if self.projectreview_set.exists():
            return self.projectreview_set.order_by('-created')[0]
        else:
            return None

    @property
    def latest_grant(self):
        if self.grant_set.exists():
            return self.grant_set.order_by('-modified')[0]
        else:
            return None

    @property
    def latest_publication(self):
        if self.publication_set.exists():
            return self.publication_set.order_by('-created')[0]
        else:
            return None

    @property
    def needs_review(self):

        if self.status.name == 'Archived':
            return False

        now = datetime.datetime.now(datetime.timezone.utc)

        if self.force_review is True:
            return True

        if not PROJECT_ENABLE_PROJECT_REVIEW:
            return False

        if self.requires_review is False:
            return False

        if self.projectreview_set.exists():
            last_review = self.projectreview_set.order_by('-created')[0]
            last_review_over_365_days = (now - last_review.created).days > 365
        else:
            last_review = None

        days_since_creation = (now - self.created).days

        if days_since_creation > 365 and last_review is None:
            return True

        if last_review and last_review_over_365_days:
            return True

        return False

    # 返回用户权限
    def user_permissions(self, user):
        if user.is_superuser:
            return list(ProjectPermission)

        user_conditions = (models.Q(status__name__in=(
            'Active', 'New')) & models.Q(user=user))
        if not self.projectuser_set.filter(user_conditions).exists():
            return []

        permissions = [ProjectPermission.USER]

        if self.projectuser_set.filter(user_conditions & models.Q(role__name='Manager')).exists():
            permissions.append(ProjectPermission.MANAGER)

        if self.projectuser_set.filter(user_conditions & models.Q(project__pi_id=user.id)).exists():
            permissions.append(ProjectPermission.PI)

        if ProjectPermission.MANAGER in permissions or ProjectPermission.MANAGER in permissions:
            permissions.append(ProjectPermission.UPDATE)

        return permissions

    def has_perm(self, user, perm):
        perms = self.user_permissions(user)
        return perm in perms

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']

        permissions = (
            ("can_view_all_projects", "可以查看所有项目"),
            ("can_review_pending_project_reviews",
             "可以审核所有待审核项目"),
        )

        verbose_name = "项目"
        verbose_name_plural = "项目管理"


class ProjectAdminComment(TimeStampedModel):
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, verbose_name="项目")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="发表者")
    comment = models.TextField(verbose_name="评论")

    def __str__(self):
        return self.comment

    class Meta:
        verbose_name = "评论"
        verbose_name_plural = "评论管理"


class ProjectUserMessage(TimeStampedModel):
    Project = models.ForeignKey(
        Project, on_delete=models.CASCADE, verbose_name="项目")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="发表者")
    is_private = models.BooleanField(default=True, verbose_name="可见性")
    message = models.TextField(verbose_name="留言")

    def __str__(self):
        return self.message

    class Meta:
        verbose_name = "留言"
        verbose_name_plural = "留言管理"


class ProjectReviewStatusChoice(TimeStampedModel):
    name = models.CharField(max_length=64, verbose_name="名称")

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name', ]
        verbose_name = "审核状态"
        verbose_name_plural = "审核状态管理"


class ProjectReview(TimeStampedModel):
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, verbose_name="项目")
    status = models.ForeignKey(
        ProjectReviewStatusChoice, on_delete=models.CASCADE, verbose_name='状态')
    reason_for_not_updating_project = models.TextField(
        blank=True, null=True, verbose_name="未升级原因")
    history = HistoricalRecords(verbose_name="历史")

    class Meta:
        verbose_name = "项目审核"
        verbose_name_plural = "项目审核"


class ProjectUserRoleChoice(TimeStampedModel):
    name = models.CharField(max_length=64, verbose_name="角色选择")

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name', ]
        verbose_name = "人员角色"
        verbose_name_plural = "人员角色"


class ProjectUserStatusChoice(TimeStampedModel):
    name = models.CharField(max_length=64, verbose_name="状态选择")

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name', ]
        verbose_name = "人员状态"
        verbose_name_plural = "人员状态"


class ProjectUser(TimeStampedModel):

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="用户")
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, verbose_name="项目")
    role = models.ForeignKey(ProjectUserRoleChoice,
                             on_delete=models.CASCADE, verbose_name="角色")
    status = models.ForeignKey(
        ProjectUserStatusChoice, on_delete=models.CASCADE, verbose_name='状态')
    enable_notifications = models.BooleanField(
        default=True, verbose_name="启用通知")
    history = HistoricalRecords(verbose_name="历史")

    def __str__(self):
        return '%s %s (%s)' % (self.user.first_name, self.user.last_name, self.user.username)

    class Meta:
        unique_together = ('user', 'project')
        verbose_name = "项目人员状态"
        verbose_name_plural = "项目人员状态"


class AttributeType(TimeStampedModel):
    name = models.CharField(max_length=64, verbose_name="属性类型")

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name', ]
        verbose_name = "属性类型"
        verbose_name_plural = "属性类型"


class ProjectAttributeType(TimeStampedModel):
    attribute_type = models.ForeignKey(
        AttributeType, on_delete=models.CASCADE, verbose_name="属性类型")
    name = models.CharField(max_length=50, verbose_name="名称")
    has_usage = models.BooleanField(default=False, verbose_name="可用性")
    is_required = models.BooleanField(default=False, verbose_name="是否需要")
    is_unique = models.BooleanField(default=False, verbose_name="是否独立")
    is_private = models.BooleanField(default=True, verbose_name="是否私有")
    is_changeable = models.BooleanField(default=False, verbose_name="是否可变")
    history = HistoricalRecords(verbose_name="历史")

    def __str__(self):
        return '%s (%s)' % (self.name, self.attribute_type.name)

    def __repr__(self) -> str:
        return str(self)

    class Meta:
        ordering = ['name', ]
        verbose_name = "项目属性类型"
        verbose_name_plural = "项目属性类型"


class ProjectAttribute(TimeStampedModel):
    proj_attr_type = models.ForeignKey(
        ProjectAttributeType, on_delete=models.CASCADE, verbose_name="项目属性")
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, verbose_name="项目")

    value = models.CharField(max_length=128, verbose_name="金额")
    history = HistoricalRecords(verbose_name="历史")

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.proj_attr_type.has_usage and not ProjectAttributeUsage.objects.filter(project_attribute=self).exists():
            ProjectAttributeUsage.objects.create(
                project_attribute=self)

    def clean(self):
        if self.proj_attr_type.is_unique and self.project.projectattribute_set.filter(proj_attr_type=self.proj_attr_type).exists():
            raise ValidationError("'{}' 已经出现在项目中".format(
                self.proj_attr_type))

bs/core/user/forms.py
from django import forms
from django.utils.html import mark_safe


class UserSearchForm(forms.Form):
    CHOICES = [
        ('username_only', '用户名查找'),
        ('all_fields', mark_safe(
            '所有字段查找<span class="text-secondary">（如果使用多个用户名进行查找，这项参数将会被忽略。）</span>'))
    ]
    q = forms.CharField(label='搜索内容', min_length=2,
                        widget=forms.Textarea(attrs={'rows': 4}), help_text='输入多个用户名并以空格间隔，可以搜索多个用户名。')

    search_by = forms.ChoiceField(
        choices=CHOICES, widget=forms.RadioSelect(), initial='username_only', label='搜索方式')

bs/core/project/templates/project/project_add_users.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
添加人员
{% endblock %}


{% block content %}
<h2>给{{project.title}}添加人员</h2>
<hr>

<div class="row">
  <div class="col">
    <form method="post" action="/search-ldap" id="post-form">
      {% csrf_token %}
      {{ user_search_form|crispy }}
      <button id="search-button" type="submit" class="btn btn-success btn-block"><i class="fas fa-search" aria-hidden="true"></i> 搜索</button>
    </form>
  </div>
</div>

<br>
<div class="row">
  <div class="col" id="search_results">
      <div class="card border-light">
        <div class="card-body">
          <div id="search_results_inner"></div>
        </div>
      </div>
  </div>
</div>
<div class="row">
  <div class="col" id="selected_users">
      <div class="card border-light">
        <div class="card-body">
        </div>
      </div>
  </div>
</div>
{% endblock %}


{% block javascript %}
  {{ block.super }}
<script>
  $("#navbar-main > ul > li.active").removeClass("active");
  $("#navbar-ldap-home").addClass("active");

  $('#post-form').on('submit', function(event){
    event.preventDefault();
    $('#search_results').show();
    $("#search_results_inner").html('<div class="alert alert-info text-center"><i class="fas fa-sync fa-spin fa-fw" aria-hidden="true"></i> 搜索中</div>')
    create_post();
  });

  function create_post() {
    q = $('#id_q').val().trim();
    search_by = $("#post-form input[type='radio']:checked").val();
    if (q.indexOf(' ') >= 0) {
      $("#id_id_search_by_0_1").prop("checked", true);
    }
    if (q.indexOf('\n') >= 0) {
      $("#id_id_search_by_0_1").prop("checked", true);
    }

    var pk = "{{ pk }}"
    $.ajax({
        url : "/project/" + pk + "/add-users-search-results/", 
        type : "POST", 
        data : { 
          q : q, 
          search_by : search_by, 
          csrfmiddlewaretoken: "{{ csrf_token }}"
        }, 
        success : function(data) {
            $('#post-text').val(''); 
            $('#search_results').show();
            $('#search_results_inner').html(data);

        },

        error : function(xhr,errmsg,err) {
            if(xhr.status == 403 || xhr.status == 401) {
                $('#search_results_inner').html("<div class='alert alert-danger'>session已过期，请重新登录<a href='#' class='close'>&times;</a></div>");
            } else {
                $('#search_results_inner').html("<div class='alert alert-danger'>出错了！ "+errmsg+
                    " <a href='#' class='close'>&times;</a></div>"); 
            }
            console.log(xhr.status + ": " + xhr.responseText);
        }
    });
  };

  $(document).ready(function(){
    $('#search_results').hide();
    $('#selected_users').hide();
    $('[data-toggle="popover"]').popover(); 
  });
</script>
{% endblock %}

bs/core/project/templates/project/project_archive.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
封存项目
{% endblock %}


{% block content %}
<h2>封存项目</h2>

<div class="card mb-3">
  <div class="card-body">
    <h3 class="card-title">
      项目负责人:
      {{ project.pi.first_name }}
      ({{ project.pi.username }})
      <a href="mailto:{{ project.pi.email }}"><i class="far fa-envelope" aria-hidden="true"></i><span class="sr-only">邮箱</span></a>
    </h3>
    <p class="card-text text-justify"><strong>描述: </strong>{{ project.description }}</p>
    <p class="card-text text-justify"><strong>学科领域: </strong>{{ project.field_of_science }}</p>
    <p class="card-text text-justify"><strong>状态: </strong>{{ project.status}}</p>
  </div>
</div>

<div class="alert alert-danger" role="alert">
  <form method="post">{% csrf_token %}
    <p>是否要封存此项目？
      这将使此项目的所有分配过期，
      这将禁用组对这些分配中资源的访问。</p>
    <input class="btn btn-danger" type="submit" value="确认" />
    <a class="btn btn-secondary" href="{% url 'project-detail' project.id %}" role="button">取消</a>
  </form>
</div>
{% endblock %}

bs/core/project/templates/project/project_archived_list.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load common_tags %}
{% load static %}


{% block title %}
项目列表
{% endblock %}


{% block content %}
<div class="card mb-3 bg-light">
  <div class="card-body">
    <div class="float-left">
      <a class="btn btn-primary" href="{% url 'project-list' %}?{{filter_parameters}}" role="button"><i class="fas fa-arrow-left" aria-hidden="true"></i> 返回</a>
    </div>
  </div>
</div>

<h2>封存项目</h2>
<hr>

{% if expand_accordion == "show" or project_list or user.is_superuser %}
  <div class="mb-3" id="accordion">
    <div class="card">
      <div class="card-header">
        <a id="expand_button" role="button" class="card-link " data-toggle="collapse" href="#collapseOne"> 
          <i class="fas fa-filter" aria-hidden="true"></i> 搜索
          <i id="plus_minus" class="fas {{expand_accordion|get_icon}} float-right"></i>
        </a>
      </div>
      <div id="collapseOne" class="collapse {{expand_accordion}}" data-parent="#accordion">
        <div class="card-body">
          <form id="filter_form" method="GET" action="{% url 'project-archived-list' %}">
            {{ project_search_form|crispy }}
            <input type="submit" class="btn btn-primary" value="搜索">
            <button id="form_reset_button" type="button" class="btn btn-secondary">重设</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <hr>
{% endif %}

{% if project_list %}
  <strong>项目: {{projects_count}}</strong>
  <div class="table-responsive">
    <table class="table table-sm">
      <thead>
        <tr>
          <th scope="col" class="text-nowrap">
            ID
            <a href="?order_by=id&direction=asc&{{filter_parameters}}"><i class="fas fa-sort-up" aria-hidden="true"></i><span class="sr-only">根据ID升序</span></a>
            <a href="?order_by=id&direction=des&{{filter_parameters}}"><i class="fas fa-sort-down" aria-hidden="true"></i><span class="sr-only">根据ID降序</span></a>
          </th>
          <th scope="col" class="text-nowrap">
            项目负责人
            <a href="?order_by=pi__username&direction=asc&{{filter_parameters}}"><i class="fas fa-sort-up" aria-hidden="true"></i><span class="sr-only">根据项目负责人升序</span></a>
            <a href="?order_by=pi__username&direction=des&{{filter_parameters}}"><i class="fas fa-sort-down" aria-hidden="true"></i><span class="sr-only">根据项目负责人降序</span></a>
          </th>
          <th scope="col">标题</th>
          <th scope="col" class="text-nowrap">
            学科领域
            <a href="?order_by=field_of_science&direction=asc&{{filter_parameters}}"><i class="fas fa-sort-up" aria-hidden="true"></i><span class="sr-only">根据学科领域升序</span></a>
            <a href="?order_by=field_of_science&direction=des&{{filter_parameters}}"><i class="fas fa-sort-down" aria-hidden="true"></i><span class="sr-only">根据学科领域降序</span></a>
          </th>
          <th scope="col" class="text-nowrap">
            状态
            <a href="?order_by=status&direction=asc&{{filter_parameters}}"><i class="fas fa-sort-up" aria-hidden="true"></i><span class="sr-only">根据状态升序</span></a>
            <a href="?order_by=status&direction=des&{{filter_parameters}}"><i class="fas fa-sort-down" aria-hidden="true"></i><span class="sr-only">根据状态降序</span></a>
          </th>
        </tr>
      </thead>
      <tbody>
        {% for project in project_list %}
          <tr>
            <td><a href="/project/{{project.id}}/">{{ project.id }}</a></td>
            <td>{{ project.pi.username }}</td>
            <td style="text-align: justify; text-justify: inter-word;"><strong>Title: </strong> {{ project.title }}
              <br> <strong>描述: </strong>{{ project.description }}</td>
            <td>{{ project.field_of_science.description }}</td>
            <td>{{ project.status.name }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% if is_paginated %} 页 {{ page_obj.number }} 共 {{ page_obj.paginator.num_pages }}
      <ul class="pagination float-right mr-3">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{filter_parameters_with_order_by}}">上一页</a></li>
        {% else %}
          <li class="page-item disabled"><a class="page-link" href="#">上一页</a></li>
        {% endif %}
        {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&{{filter_parameters_with_order_by}}">下一页</a></li>
        {% else %}
          <li class="page-item disabled"><a class="page-link" href="#">下一页</a></li>
        {% endif %}
      </ul>
    {% endif %}
  </div>
{% else %}
  <div class="alert alert-info">
    没有封存项目！
  </div>
{% endif %}

<script>
  $(document).on('click', '#form_reset_button', function() {
    resetForm($('#filter_form'));
  });

  function resetForm($form) {
    $form.find('input:text, textarea').val('');
  };

  $("#expand_button").click(function() {
    $('#collapseOne').collapse();
    icon = $(this).find("i");
    icon.toggleClass("fa-plus fa-minus");
  });
</script>
{% endblock %}

bs/core/project/templates/project/project_attribute_create.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load common_tags %}
{% load static %}


{% block title %}
添加项目属性
{% endblock %}


{% block content %}
<h2>给{{ project }}添加项目属性</h2>

<form method="post">
	{% csrf_token %}
	{{ form | crispy }}
	<input class="btn btn-success" type="submit" value="添加" />
	<a class="btn btn-secondary" href="{% url 'project-detail' project.pk %}" role="button">返回</a><br>
</form>
{% endblock %}

bs/core/project/templates/project/project_attribute_delete.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load common_tags %}
{% load static %}


{% block title %}
删除项目属性
{% endblock %}


{% block content %}
<h2>从{{ project }}删除项目属性</h2>

{% if formset %}
  <div class="card border-light">
    <div class="card-body">
      <form action="{% url 'project-attribute-delete' project.pk %}" method="post">
        {% csrf_token %}
        <div class="table-responsive">
          <table class="table table-sm table-hover">
            <thead>
              <tr>
                <th>
                  <input type="checkbox" class="check" id="selectAll">
                </th>
                <th scope="col">类型</th>
                <th scope="col">值</th>
              </tr>
            </thead>
            <tbody>
              {% for form in formset %}
                <tr>
                  <td>{{ form.selected }}</td>
                  <td>{{ form.name.value }}</td>
                  <td>{{ form.value.value }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        {{ formset.management_form }}
        <div>
          <button type="submit" class="btn btn-danger"><i class="fas fa-minus" aria-hidden="true"></i> 删除所选属性</button>
          <a class="btn btn-secondary" href="{% url 'project-detail' project.pk %}" role="button"><i
              class="fas fa-long-arrow-left" aria-hidden="true"></i> 返回</a>
          <br>
        </div>
      </form>
    </div>
  </div>
{% else %}
  <div class="alert alert-info">
    没有属性可删除！
  </div>
  <a class="btn btn-secondary mb-3" href="{% url 'project-detail' project.pk %}" role="button"><i
      class="fas fa-long-arrow-left" aria-hidden="true"></i> 返回</a>
{% endif %}

<script>
  $("#selectAll").click(function () {
    $("input[name^='attributeform-']").prop('checked', $(this).prop('checked'));
  });

  $("input[name^='attributeform-']").click(function (ele) {
    var id = $(this).attr('id');
    if (id != "selectAll") {
      $("#selectAll").prop('checked', false);
    }
  });
</script>
{% endblock %}

bs/core/project/templates/project/project_create_form.html
{% extends "common/base.html" %} 
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
创建项目
{% endblock %}


{% block content %}
 <form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <input class="btn btn-primary" type="submit" value="保存" />
  <a class="btn btn-secondary" href="{% url 'project-list' %}" role="button">取消</a>
</form>

<script>
  $(document).ready(function() {
    $('#id_field_of_science').select2();
  });
</script>
{% endblock %}

bs/core/project/templates/project/project_note_create.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load common_tags %}
{% load static %}


{% block title %}
添加项目通知
{% endblock %}


{% block content %}
<h2>给{{project.title}}添加通知，项目负责人为{{ project.pi.first_name }}({{ project.pi.username }})</h2>

<form method="post">
  {% csrf_token %}
  {{form |crispy}}
  <input class="btn btn-success" type="submit" value="添加" />
  <a class="btn btn-secondary" href="{% url 'project-detail' project.pk %}" role="button">返回</a><br>
</form>
{% endblock %}